name: Release assets to jsDelivr

on:
  release:
    branch: main
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Version
        id: set_version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Build assets
        run: npm run build

      - name: Deploy to jsDelivr
        uses: JSdelivr/jsdelivr-action@1.0.1
        with:
          path: "dist"
          repo: "reminia/translateit-btn"
          version: ${{ steps.set_version.outputs.version }}
