name: Release assets

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build project
        run: npm run build

      - name: Set Version
        run: echo "::set-output name=version::$(node -p "require('./package.json').version")"

      - name: Release assets
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*"
          name: ${{ steps.set_version.outputs.version }}
          tag: ${{ steps.set_version.outputs.version }}
          allowUpdates: true